name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Send request to '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the OCR service?
      options:
        - Docker Compose
        - Docker (standalone)
        - Native Python
        - Kubernetes
        - Other
    validations:
      required: true

  - type: dropdown
    id: ocr-engine
    attributes:
      label: OCR Engine
      description: Which OCR engine were you using when the bug occurred?
      options:
        - Tesseract
        - EasyOCR
        - ocrmac (macOS)
        - Not sure
        - Not applicable
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the OCR service are you running?
      placeholder: "e.g., 1.1.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using (if applicable)?
      options:
        - Python 3.11
        - Python 3.12
        - Not applicable (Docker)
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, example files, etc.)

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OCRBridge/ocr-service/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
